### PR TITLE
Migrate to next-with-redux:v9

### PR DESCRIPTION
**Pull request by Guneetgstar**

### CODE REVIEW

**Comment by joaopaulomoraes** [comment]
Thanks for the PR, @Guneetgstar.

I have only two observations. It seems to me that we never have a call being fired on the server side (in this case the first) and this is very important, especially for real-world applications. Another point is the inclusion of comments and renown of the `increment` and `decrement` functions.

What do you think? Please don't take it as a criticism, I'm just thinking about improving the boilerplate with your help. ;)

**Comment by Guneetgstar** [comment]
Sorry but I am not able to understand what call you are referring to? There is a major change in `next-redux-wrapper` [5x->6x](https://github.com/kirill-konshin/next-redux-wrapper#upgrade-from-5x-to-6x) and now `getInitialProps` will be called inside the wrapper and if we wrap the `_App` itself under the redux wrapper then i think every call made to load the pages would be carring the props from `getInitialProps`  means server would always render a new page.  I have just started a project in next.js so i might be wrong.
 Although i have a new pull request for this project if you would like to add. I have made some changes with fork to include `connected-next-router` in the app. These are very basic configs which are must for every app and we can merge it.

**Comment by Guneetgstar** [comment]
Are you referring to this?
https://github.com/joaopaulomoraes/nextjs-with-redux-and-material-ui/blob/2c07deb0c523888a217c89e8c09e3564c2cf1600/pages/index.js#L76
Yeah that made me think about it for a minute  that why the action from the server is never dispatched. I think there must be another way to get the desired outcome. I just didn't have a use case so I didn't try to find 😉

**Comment by joaopaulomoraes** [comment]
Any contribution is certainly welcome, even for a simple boilerplate. Thank you!

**Comment by Guneetgstar** [comment]
> There is a major change in `next-redux-wrapper` [5x->6x](https://github.com/kirill-konshin/next-redux-wrapper#upgrade-from-5x-to-6x) and now `getInitialProps` will be called inside the wrapper and if we wrap the `_App` itself under the redux wrapper then i think every call made to load the pages would be carring the props from `getInitialProps` means server would always render a new page. I have just started a project in next.js so i might be wrong.

Another benefit that I got reading the docs again following your remark is that I found how to use `Automatic Static Optimisation` even with `redux` in next:
> ⚠️ Next.js provides generic getInitialProps when using class MyApp extends App which will be picked up by wrapper, so you must not extend App as you'll be opted out of Automatic Static Optimization: https://err.sh/next.js/opt-out-auto-static-optimization. Just export a regular Functional Component as in the example above.

So what I really did wrong is extend the `next/app` and wrap it inside `next-redux-wrapper` which has now made this example server-side rendered. This can be fixed easily in another PR if you would like to.

**Pull request merged**
