### PR TITLE
Added connected-next-router

### PR DESCRIPTION
**Pull request by Guneetgstar**
Here is another one 🎉🎉

### CODE REVIEW

**Comment by Guneetgstar** [comment]
Hi @joaopaulomoraes before committing this PR can you please verify if the `HYDRATE` state is being handled appropriately. Thanks

**Comment by joaopaulomoraes** [comment]
Hi @Guneetgstar ! I've been a little busy these days, but I appreciate your enthusiasm.

Some files are in conflict with this PR and the first dispatch must actually be executed from the server, it cannot be removed.

Please don't be upset, but I believe you can fork this project and add `connected-next-router` in order to maintain it and make it available to other people, since this project is just an example of how to use next with redux and material-ui.

I will close this PR for now. Thanks!

**Comment by Guneetgstar** [comment]
Thanks @joaopaulomoraes for everything you said its just that I like to contribute where its possible because this community is the only reason why we can make such robust apps in no time.
Although I do want to point you for some of your words:
> 
> Some files are in conflict with this PR and the first dispatch must actually be executed from the server, it cannot be removed.

If you see the docs [here](https://github.com/kirill-konshin/next-redux-wrapper#how-it-works) in the **Phase 2** they have explained that:
> The wrapper dispatches HYDRATE action with the previous store's state as payload

So you are right the first dispatch should be from the server but this `wrapper` is doing this for us already hence we can omit dispatching action manually.

**Comment by Guneetgstar** [comment]
> I believe you can fork this project and add `connected-next-router` in order to maintain it and make it available to other people, since this project is just an example of how to use next with redux and material-ui.

Actually I was planning not to fork but create a boilerplate instead as for me migrating from client-side rendering to `next.js` took almost 1 week to achieve the exact behaviour and it might still be having bugs and all that for an app of around 10-20 pages only! It would be great if you can help pointing out the mistakes as I am new to `next.js`

**Pull request closed without merging**
